database_file: /data/timetrap.db
round_in_seconds: 900
append_notes_delimiter: ' '
formatter_search_paths:
  - /data/formatters
default_formatter: text
auto_sheet: dotfiles
auto_sheet_search_paths:
  - /data/auto_sheets
default_command: ~
auto_checkout: false
require_note: false
